name: Playwright Tests

on:
  # Run this workflow on pushes and pull requests to the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the latest code from the repository
    - uses: actions/checkout@v3

    # Set up Node.js environment with the specified version
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.4.1'

    # Install project dependencies using npm
    - name: Install dependencies
      run: npm ci

    # Install Playwright browsers along with necessary dependencies
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # Select a random browser from the list and set it as an environment variable
    - name: Select random browser
      id: select-browser
      run: |
        browsers=("chromium" "firefox" "webkit")
        selected_browser=${browsers[$RANDOM % ${#browsers[@]}]}
        echo "selected_browser=$selected_browser" >> $GITHUB_ENV

    # Run Playwright smoke tests on push events
    - name: Run Playwright Tests on Push
      if: github.event_name == 'push'
      env:
        CI: true
        CI_WORKERS: 4
        CI_RETRIES: 1
        CI_BROWSER: ${{ env.selected_browser }}
      run: npm run test:smoke

    # Run the full suite of Playwright tests on pull request events
    - name: Run Playwright Tests on Pull Request
      if: github.event_name == 'pull_request'
      env:
        CI: true
        CI_WORKERS: 4
        CI_RETRIES: 2
        CI_BROWSER: ${{ env.selected_browser }}
      run: npm run test
